gull:
  authport: 9000
  logouturl: http://localhost:9000/auth/realms/master/protocol/openid-connect/logout
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        registration:
          login:
            provider: keycloak
            client-id: gull-client
            client-secret: 863fa419-703d-41ac-bc5e-0b07a8125231
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          keycloak:
            token-uri: http://localhost:${gull.authport}/auth/realms/master/protocol/openid-connect/token
            authorization-uri: http://localhost:${gull.authport}/auth/realms/master/protocol/openid-connect/auth
            user-info-uri: http://localhost:${gull.authport}/auth/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: http://localhost:${gull.authport}/auth/realms/master/protocol/openid-connect/certs
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: logdebug
logging:
  level:
    devs.mrp.gullproject: DEBUG
    org.springframework.web: DEBUG
    org.springframework.test: DEBUG
    org.springframework.security: DEBUG