gull:
  authport: 9000
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        registration:
          gull-client:
            provider: keycloak
            client-id: gull-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
        provider:
          keycloak:
            token-uri: http://localhost:${gull.authport}/auth/realms/master/protocol/openid-connect/token
            authorization-uri: http://localhost:${gull.authport}/auth/realms/master/protocol/openid-connect/auth
            user-info-uri: http://localhost:${gull.authport}/auth/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: gull-client
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: logdebug
logging:
  level:
    devs.mrp.gullproject: DEBUG
    org.springframework.web: DEBUG
    org.springframework.test: DEBUG