spring:
  application:
    name: gateway-service
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: logdebug
logging:
  level:
    devs.mrp.gullproject: DEBUG
    org.springframework.web: DEBUG
    org.springframework.test: DEBUG