gull:
  authscheme: http
  authport: 9000
  authhost: localhost
  authclient: gull-campo-service
  authsecret: 73fb0fb7-9aab-42f0-bc7b-66f476bde874
  eurekauser: mockUser
  eurekapass: mockPass
  eurekascheme: http
  eurekahost: localhost
  eurekaport: 8761
jwk:
  endpoint: ${gull.authscheme}://${gull.authhost}:${gull.authport}/auth/realms/master/protocol/openid-connect/certs
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
    rest:
      base-path: /api
  application:
    name: campo-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${gull.authscheme}://${gull.authhost}:${gull.authport}/auth/realms/master
      client:
        registration:
          campo:
            provider: keycloak
            client-id: ${gull.authclient}
            client-secret: ${gull.authsecret}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: ${gull.authscheme}://${gull.authhost}:${gull.authport}/auth/realms/master/protocol/openid-connect/token
            authorization-uri: ${gull.authscheme}://${gull.authhost}:${gull.authport}/auth/realms/master/protocol/openid-connect/auth
            user-info-uri: ${gull.authscheme}://${gull.authhost}:${gull.authport}/auth/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: ${gull.authscheme}://${gull.authhost}:${gull.authport}/auth/realms/master/protocol/openid-connect/certs
server:
  port: 0
eureka:
  instance:
    hostname: ${gull.eurekahost}
  client:
    service-url:
      defaultZone: ${gull.eurekascheme}://${gull.eurekauser}:${gull.eurekapass}@${gull.eurekahost}:${gull.eurekaport}/eureka/
      
---
spring:
  config:
    activate:
      on-profile: logdebug
logging:
  level:
    devs.mrp.gullproject: DEBUG
    org.springframework.web: DEBUG
    org.springframework.test: DEBUG
    org.thymeleaf: DEBUG

