gull:
  authport: 9000
jwk:
  endpoint: http://localhost:${gull.authport}/auth/realms/master/protocol/openid-connect/certs
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
    rest:
      base-path: /api
  application:
    name: campo-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${gull.authport}/auth/realms/master
      client:
        registration:
          campo:
            provider: keycloak
            client-id: gull-campo-service
            client-secret: 73fb0fb7-9aab-42f0-bc7b-66f476bde874
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            token-uri: http://localhost:${gull.authport}/auth/realms/master/protocol/openid-connect/token
            authorization-uri: http://localhost:${gull.authport}/auth/realms/master/protocol/openid-connect/auth
            user-info-uri: http://localhost:${gull.authport}/auth/realms/master/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            jwk-set-uri: http://localhost:${gull.authport}/auth/realms/master/protocol/openid-connect/certs
server:
  port: 0
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
---
spring:
  config:
    activate:
      on-profile: logdebug
logging:
  level:
    devs.mrp.gullproject: DEBUG
    org.springframework.web: DEBUG
    org.springframework.test: DEBUG
    org.thymeleaf: DEBUG

