spring:
  data:
    rest:
      base-path: /api
  application:
    name: campo-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  level:
    org.springframework.webflux: DEBUG
    org.springframework.web: DEBUG
    org.springframework.test: DEBUG
