spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
    rest:
      base-path: /api
  application:
    name: AUTH-SERVICE
server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
---
spring:
  config:
    activate:
      on-profile: logdebug
logging:
  level:
    root: DEBUG
    devs.mrp.gullproject: DEBUG
    org.springframework.web: DEBUG
    org.springframework.test: DEBUG
    org.springframework.security: DEBUG
    org.thymeleaf: DEBUG

