gull:
  authscheme: http
  authport: 9000
  authhost: localhost
  eurekauser: mockUser
  eurekapass: mockPass
  eurekascheme: http
  eurekahost: localhost
  eurekaport: 8761
jwk:
  endpoint: ${gull.authscheme}://${gull.authhost}:${gull.authport}/auth/realms/master/protocol/openid-connect/certs
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
  application:
    name: atributo-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${gull.authscheme}://${gull.authhost}:${gull.authport}/auth/realms/master
server:
  port: 0
eureka:
  instance:
    hostname: ${gull.eurekahost}
  client:
    service-url:
      defaultZone: ${gull.eurekascheme}://${gull.eurekauser}:${gull.eurekapass}@${gull.eurekahost}:${gull.eurekaport}/eureka/
      
---
spring:
  config:
    activate:
      on-profile: logdebug
logging:
  level:
    devs.mrp.gullproject: DEBUG
    org.springframework.web: DEBUG
    org.springframework.test: DEBUG
    org.thymeleaf: DEBUG
    org.springframework.security: DEBUG
    