gull:
  authport: 9000
jwk:
  endpoint: http://localhost:${gull.authport}/auth/realms/master/protocol/openid-connect/certs
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
  application:
    name: atributo-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${gull.authport}/auth/realms/master
server:
  port: 0
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
---
spring:
  config:
    activate:
      on-profile: logdebug
logging:
  level:
    devs.mrp.gullproject: DEBUG
    org.springframework.web: DEBUG
    org.springframework.test: DEBUG
    org.thymeleaf: DEBUG
    org.springframework.security: DEBUG
    