gull:
  user: mockUser
  secret: mockPass
  schema: http
  host: localhost
spring:
  application:
    name: discovery-service
  security:
    user:
      name: ${gull.user}
      password: ${gull.secret}
eureka:
  instance:
    hostname: ${gull.host}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${gull.schema}://${gull.user}:${gull.secret}@${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false
server:
   port: 8761
